---
- hosts: cisco_routers
  gather_facts: yes 
  connection: network_cli

  tasks:
    - name: Gather running configuration
      ios_command:
        commands:
          - show running
      register: running_config

    - name: Flag weak community strings
      fail:
        msg: "Weak SNMP community string found!"
      when: "'snmp-server community public' in running_config"

    - name: Fail if 'service password-encryption' is not found
      fail:
          msg: "Passwords are not encrypted!"
      when: "'password-encryption' in running_config"

    - name: Check NTP server configuration
      fail:
        msg: "NTP configuration missing or incomplete!" 
      when: "'ntp server' not in running_config"
