---
- hosts: cisco_routers
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Backup configuration
      ios_config:
        backup: yes

    - name: Example - Change SNMP configuration
      ios_config:
        lines:
          - snmp-server community test RO

    - name: Restore configuration (if needed)
      ios_config:
        backup: yes
        restore: yes
