---
- name: Verificar y corregir políticas de seguridad en routers Cisco
  hosts: cisco_routers
  gather_facts: no
  vars:
    admin_username: admin
    admin_password: password123

  tasks:
    - name: Check if user "admin" exists
      cisco.ios.ios_command:
        commands: show running-config | i username
      register: user_exists_output

    - name: Create user "admin" if it doesn't exist
      cisco.ios.ios_config:
        lines:
          - username {{ admin_username }} secret {{ admin_password }}
      when: "'admin' not in user_exists_output.stdout_lines"