---
- name: Configurar Routers Cisco
  hosts: cisco_routers
  connection: network_cli
  gather_facts: no
  vars_files:
    - variables.yml
    - vars_vault.yml
  tasks:
    - name: Generando la configuración del router en base la Plantilla
      template:
       src: "templates/template_{{ inventory_hostname }}.j2"
       dest: "/tmp/{{ inventory_hostname }}_config.txt"

    - name: Empujar la configuración hacia el Router
      ios_config:
        src: "/tmp/{{ inventory_hostname }}_config.txt"