---
- name: Colectar las variables para el Playbook
  hosts: all, localhost
  gather_facts: no
  vars_files:
    - ./vars_vault.yml
  tasks:
   - name: Obteniendo la Fecha actual
     local_action: command date +%Y%m%d
     register: timedate
  
   - name: Creando Variable que Almacene la Fecha Actual
     set_fact: 
      timestamp: "{{ timedate.stdout }}"
      cacheable: yes
      
- name: Generar de Backups de la Configuración
  hosts: cisco_ios_routers
  gather_facts: no
  connection: network_cli
  vars_files:
    - ./vars_vault.yml
  tasks:

   - name: Colectando Backups de los Routers y Almacenarlos en Archivos con sus Nombres
     ios_config:
      backup: yes
      backup_options:
        filename: "{{ inventory_hostname }}_{{ timestamp }}.txt"
        dir_path: /tmp/backups_cisco_{{ timestamp }}/
     ignore_errors: yes

- name: Crear un archivo Zip del directorio que tiene los Backups
  hosts: localhost
  gather_facts: no
  tasks:
   - name: Creando archivo Zip
     connection: local
     archive:
        path:
          - /tmp/backups_cisco_{{ timestamp }}
        dest: /tmp/bkps_cisco_{{ timestamp }}.zip
        format: zip
      
- name: Copiar Archivo Zip a Servidor SFTP
  hosts: SFTP-S
  gather_facts: no
  vars_files:
    - ./vars_vault.yml
  tasks:      
   - name: Copiando archivos a Servidor SFTP
     copy:
      src: "/tmp/bkps_cisco_{{ timestamp }}.zip"
      dest: "/home/codingnetworks/bkps_cisco_{{ timestamp }}.zip"
      