[cisco_routers]
router1 ansible_host=192.168.56.11
router2 ansible_host=192.168.56.12

[cisco_routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user=codingnetworks
ansible_password=coding21
# ansible_become=yes
# ansible_become_method=enable

subnet_id=56