[sftp_servers]
SFTP-S ansible_host=192.168.56.21 ansible_user="{{ cod_remote_user }}" ansible_password="{{ cod_remote_pass }}" ansible_connection=ssh

[cisco_ios_routers:vars]
ansible_connection=ansible.netcommon.network_cli
ansible_network_os=cisco.ios.ios
ansible_user="{{ cod_remote_user }}"
ansible_password="{{ cod_remote_pass }}"
ansible_become=yes
ansible_become_method=enable

[cisco_ios_routers]
router1 ansible_host=192.168.56.11
router2 ansible_host=192.168.56.12


